gText_Birch_Welcome::
	.string "Steven! In der Zeit wo du 1kg\n"
	.string "abgenommen hast, hab ich eine komplette\l"
	.string "Geschlechtsumwandlung durchgezogen.\p"
	.string "Richtig. Ich bins. Deine Mutter.\p"
	.string "Wolltest du dieses Jahr nicht ins\n"
	.string "Fitnessstudio gehen?!\p"
	.string "Es reicht mir mit dir.\n"
	.string "Du meldest dich jetzt sofort dafür an.\p"
	.string "Und als Beweis zeigst du mir hinterher\n"
	.string "die 8 Orden aller Gyms, auch bekannt\l"
	.string "als Fitnessstudio.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Nachher siehst du noch aus wie er!\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Steven, ich habe hier einen Brief\n"
	.string "an dich adressiert gefunden.\p"
	.string "Die Absender sind\n"
	.string "Palex, Tim und Niklas.\l"
	.string "In dem Brief steht:\p"
	.string ">Moin Steven.\n"
	.string ">Du dachtest, Radical Red war schlimm..\l"
	.string ">Aber da müssen wir dich leider\l"
	.string ">enttäuschen.\p"
	.string ">Willkommen in Pokemon Fertig.\n"
	.string ">Das Spiel, was dich nicht nur ingame\l"
	.string ">an deine Grenzen bringt.\p"
	.string ">Wir haben definitiv zu viel Langeweile.\n"
	.string ">Viel Spaß mit der Scheiße.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Meine Demenz kickt gerade wieder übel.\p$"

gText_Birch_BoyOrGirl::
	.string "Stehst du auf boys?\n"
	.string "Oder eher so auf girls?$"

gText_Birch_WhatsYourName::
	.string "Verstehe, solang sie noch 15 ist.\p"
	.string "Wie hab ich mein Kind nochmal genannt?\p$"

gText_Birch_SoItsPlayer::
	.string "Stimmt, der fette {PLAYER}{KUN}?\p$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p$"

gText_Birch_AreYouReady::
	.string "Denk dran, wir wohnen in dem unteren\n"
	.string "Haus in Magdeburg.\p"
	.string "Und ich warne dich.\n"
	.string "Wenn ich sehe, dass du wieder Frösche\p"
	.string "über den LKW wirfst, knallt es.\p"
	.string "Und jetzt geh mal abnehmen!\p"
	.string "$"
