gText_WouldYouLikeToRestYourPkmn::
	.string "Hallo und willkommen beim\n"
	.string "Arbeitsamt Magdeburg.\p"
	.string "Du bist hier um dein Bürgergeld\n"
	.string "abzuholen?$"

gText_IllTakeYourPkmn::
	.string "Okay, dann brauche ich einmal\n"
	.string "deine Unterlagen.$"

gText_RestoredPkmnToFullHealth::
	.string "Du hast diesen Monat schon dein\n"
	.string "Geld bekommen. Wenn dir das nicht\l"
	.string "reicht, würde ich es mal mit\l"
	.string "Arbeiten versuchen.$"

gText_WeHopeToSeeYouAgain::
	.string "Hoffentlich sehen wir uns nicht wieder!$"

gText_WelcomeCutShort::
	.string "Hallo und willkommen beim\n"
	.string "Arbeitsamt Magdeburg.\p"
	.string "Du bist hier um dein Bürgergeld\n"
	.string "abzuholen?$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, dann brauche ich einmal\n"
	.string "deine Unterlagen.$"

gText_ThankYouForWaiting::
	.string "Du hast diesen Monat schon dein\n"
	.string "Geld bekommen. Wenn dir das nicht\l"
	.string "reicht, würde ich es mal mit\l"
	.string "Arbeiten versuchen.$"

gText_WeHopeToSeeYouAgain2::
	.string "Hoffentlich sehen wir uns nicht wieder!$"
